# Generated by Django 6.0.2 on 2026-03-25 07:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_alter_journalitem_options'),
        ('rentals', '0016_rental_deposit_journal_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Deposit Amount')),
                ('deposit_date', models.DateField(verbose_name='Deposit Date')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque')], default='cash', max_length=20, verbose_name='Method')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Reference')),
                ('status', models.CharField(choices=[('received', 'Received'), ('partially_refunded', 'Partially Refunded'), ('fully_refunded', 'Fully Refunded')], default='received', max_length=30, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_record', to='accounting.journalentry', verbose_name='Journal Entry')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='rentals.rental', verbose_name='Rental Contract')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'ordering': ['-deposit_date', '-id'],
                'indexes': [models.Index(fields=['status'], name='deposits_de_status_091e76_idx'), models.Index(fields=['deposit_date'], name='deposits_de_deposit_6bf1d6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='deposit_amount_gt_zero')],
            },
        ),
    ]
