# Generated by Django 6.0.2 on 2026-03-25 09:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_journalitem_options'),
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Refund Amount')),
                ('refund_date', models.DateField(verbose_name='Refund Date')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque')], default='cash', max_length=20, verbose_name='Method')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='deposits.deposit', verbose_name='Deposit')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_refund_record', to='accounting.journalentry', verbose_name='Journal Entry')),
            ],
            options={
                'verbose_name': 'Deposit Refund',
                'verbose_name_plural': 'Deposit Refunds',
                'ordering': ['-refund_date', '-id'],
                'indexes': [models.Index(fields=['refund_date'], name='deposits_de_refund__d7c406_idx'), models.Index(fields=['deposit'], name='deposits_de_deposit_6ee3fe_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='deposit_refund_amount_gt_zero')],
            },
        ),
    ]
