# Generated by Django 6.0.2 on 2026-03-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_depositrefund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending_collection', 'Pending Collection'), ('received', 'Received'), ('partially_refunded', 'Partially Refunded'), ('fully_refunded', 'Fully Refunded')], default='pending_collection', max_length=30, verbose_name='Status'),
        ),
    ]
