# Generated by Django 6.0.2 on 2026-04-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0005_deposit_currency_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='amount_usd',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='exchange_rate_to_usd',
        ),
    ]
