# Generated by Django 6.0.2 on 2026-03-04 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0002_contract'),
        ('rentals', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'عملية تأجير', 'verbose_name_plural': 'عمليات التأجير'},
        ),
        migrations.RemoveField(
            model_name='rental',
            name='late_penalty_percentage',
        ),
        migrations.AddField(
            model_name='rental',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='سعر اليوم المتفق عليه', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='net_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='الإجمالي النهائي'),
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_days',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='عدد الأيام'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإرجاع الفعلي'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(verbose_name='Return Date المتوقع'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(verbose_name='Pickup Date'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='traffic_fines',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المخالفات'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='نسبة Tax % %'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='السيارة'),
        ),
    ]
