# Generated by Django 6.0.2 on 2026-03-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر اليوم'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='net_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='الإجمالي الكلي'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='Tax % %'),
        ),
    ]
