# Generated by Django 6.0.2 on 2026-03-04 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0003_customer_address_customer_nationality_and_more'),
        ('rentals', '0003_alter_rental_daily_rate_alter_rental_net_total_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Rental Operation', 'verbose_name_plural': 'Rental Operations'},
        ),
        migrations.AlterField(
            model_name='rental',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Return Date'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Daily Rate'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(verbose_name='Expected Return Date'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='net_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Net Total'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_days',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Rental Days'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(verbose_name='Pickup Date'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='traffic_fines',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Traffic Fines'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='VAT %'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='Vehicle'),
        ),
    ]
