# Generated by Django 6.0.2 on 2026-03-05 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_rental_options_alter_rental_actual_return_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rentals/attachments/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rentals.rental')),
            ],
        ),
    ]
