# Generated by Django 6.0.2 on 2026-03-09 06:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0004_alter_customer_options_customer_company_name_and_more'),
        ('rentals', '0005_rentalattachment'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rental Operation', 'verbose_name_plural': 'Rental Operations'},
        ),
        migrations.RemoveField(
            model_name='rental',
            name='is_active',
        ),
        migrations.AddField(
            model_name='rental',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='Monthly Auto Renew'),
        ),
        migrations.AddField(
            model_name='rental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Contract Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='actual_return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Return Date & Time'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateTimeField(verbose_name='Expected Return Date & Time'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateTimeField(verbose_name='Pickup Date & Time'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicle', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='rentalattachment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rentalattachment',
            name='file',
            field=models.FileField(upload_to='rentals/attachments/', verbose_name='Attachment File'),
        ),
    ]
