# Generated by Django 6.0.2 on 2026-03-09 07:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0004_alter_customer_options_customer_company_name_and_more'),
        ('rentals', '0006_alter_rental_options_remove_rental_is_active_and_more'),
        ('vehicles', '0002_alter_vehicle_options_vehicle_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={},
        ),
        migrations.RemoveField(
            model_name='rental',
            name='actual_return_date',
        ),
        migrations.RemoveField(
            model_name='rentalattachment',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='rental',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='تجديد تلقائي'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Daily Rate'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateTimeField(verbose_name='Return Date'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='net_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_days',
            field=models.IntegerField(default=0, verbose_name='الأيام'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateTimeField(verbose_name='Pickup Date'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='traffic_fines',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المخالفات'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Tax % %'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='rentalattachment',
            name='description',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentalattachment',
            name='file',
            field=models.FileField(upload_to='rentals/attachments/'),
        ),
        migrations.CreateModel(
            name='RentalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='العملية')),
                ('details', models.TextField(verbose_name='التفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rentals.rental')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
        ),
    ]
