# Generated by Django 6.0.2 on 2026-03-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_rental_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('active', 'نشط - Active'), ('completed', 'مكتمل - Completed'), ('cancelled', 'ملغي - Cancelled')], default='active', max_length=20, verbose_name='حالة العقد'),
        ),
    ]
