# Generated by Django 6.0.2 on 2026-03-12 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_options_customer_company_name_and_more'),
        ('rentals', '0008_rental_status'),
        ('vehicles', '0002_alter_vehicle_options_vehicle_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rental', 'verbose_name_plural': 'Rentals'},
        ),
        migrations.AlterModelOptions(
            name='rentalattachment',
            options={'verbose_name': 'Rental Attachment', 'verbose_name_plural': 'Rental Attachments'},
        ),
        migrations.AlterModelOptions(
            name='rentallog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rental Log', 'verbose_name_plural': 'Rental Logs'},
        ),
        migrations.AddField(
            model_name='rental',
            name='actual_return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Return Date'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='Auto Renew'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateTimeField(verbose_name='Expected Return Date'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='net_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Total'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_days',
            field=models.IntegerField(default=0, verbose_name='Rental Days'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Rental Status'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='traffic_fines',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Traffic Fines'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tax %'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='vehicles.vehicle', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='rentalattachment',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rentalattachment',
            name='file',
            field=models.FileField(upload_to='rentals/attachments/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='rentalattachment',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rentals.rental', verbose_name='Rental'),
        ),
        migrations.AlterField(
            model_name='rentallog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='rentallog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='rentallog',
            name='details',
            field=models.TextField(verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='rentallog',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rentals.rental', verbose_name='Rental'),
        ),
        migrations.AlterField(
            model_name='rentallog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
