# Generated by Django 6.0.2 on 2026-03-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_alter_rental_options_alter_rentalattachment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='pickup_odometer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pickup Odometer (KM)'),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_odometer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Return Odometer (KM)'),
        ),
    ]
