# Generated by Django 6.0.2 on 2026-03-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_rental_pickup_odometer_rental_return_odometer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='damage_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Damage Fees'),
        ),
        migrations.AddField(
            model_name='rental',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Other Charges'),
        ),
    ]
