# Generated by Django 6.0.2 on 2026-03-18 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('rentals', '0011_rental_damage_fees_rental_other_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='accounting_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10, verbose_name='Accounting State'),
        ),
        migrations.AddField(
            model_name='rental',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_record', to='accounting.journalentry', verbose_name='Journal Entry'),
        ),
    ]
