# Generated by Django 6.0.2 on 2026-03-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_rental_accounting_state_rental_journal_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalattachment',
            options={},
        ),
    ]
