# Generated by Django 6.0.2 on 2026-03-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_alter_rentalattachment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalattachment',
            options={'verbose_name': 'Rental Attachment', 'verbose_name_plural': 'Rental Attachments'},
        ),
        migrations.AddField(
            model_name='rental',
            name='contract_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Contract Number'),
        ),
    ]
