# Generated by Django 6.0.2 on 2026-03-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0014_alter_rentalattachment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deposit Amount'),
        ),
    ]
