# Generated by Django 6.0.2 on 2026-03-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0016_rental_deposit_journal_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-created_at'], 'permissions': (('post_rental', 'Can post rental'), ('collect_contract_and_deposit', 'Can collect contract and deposit'), ('collect_traffic_fine', 'Can collect traffic fine'), ('return_vehicle', 'Can return vehicle')), 'verbose_name': 'Rental', 'verbose_name_plural': 'Rentals'},
        ),
    ]
