# Generated by Django 6.0.2 on 2026-04-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0018_rental_additional_driver_rental_contract_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-created_at'], 'permissions': (('post_rental', 'Can post rental'), ('collect_contract_and_deposit', 'Can collect contract and deposit'), ('collect_traffic_fine', 'Can collect traffic fine'), ('return_vehicle', 'Can return vehicle'), ('cancel_rental', 'Can cancel rental')), 'verbose_name': 'Rental', 'verbose_name_plural': 'Rentals'},
        ),
    ]
