# Generated by Django 6.0.2 on 2026-04-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0020_rental_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='currency_code',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('IQD', 'Iraqi Dinar'), ('SYP', 'Syrian Pound'), ('AED', 'UAE Dirham')], default='USD', max_length=3, verbose_name='Currency'),
        ),
    ]
