# Generated by Django 6.0.2 on 2026-04-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0021_alter_rental_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='baby_seat_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Baby Seat Fee'),
        ),
        migrations.AddField(
            model_name='rental',
            name='insurance_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Insurance Fee'),
        ),
    ]
