# Generated by Django 6.0.2 on 2026-03-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_address_customer_nationality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company Name (e.g. Coca-Cola)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate / Company')], default='individual', max_length=20, verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full Name / Person in Charge'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='license_number',
            field=models.CharField(max_length=100, verbose_name='License / ID Number'),
        ),
    ]
