# Generated by Django 6.0.2 on 2026-03-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_options_customer_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Passport Expiry Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Passport Issue Date'),
        ),
    ]
