# Generated by Django 6.0.2 on 2026-03-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_passport_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='driving_license_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Driving License Expiry Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='driving_license_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Driving License Issue Date'),
        ),
    ]
