# Generated by Django 6.0.2 on 2026-03-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_expense_reference_alter_journalentry_entry_no_and_more'),
        ('customers', '0005_customer_passport_expiry_date_and_more'),
        ('invoices', '0002_alter_invoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_receivable_entries', to='accounting.account', verbose_name='Receivable Account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_revenue_entries', to='accounting.account', verbose_name='Revenue Account'),
        ),
    ]
