# Generated by Django 6.0.2 on 2026-03-20 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_expense_reference_alter_journalentry_entry_no_and_more'),
        ('invoices', '0003_invoice_customer_invoice_receivable_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='journal_entry',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_invoices', to='accounting.journalentry', verbose_name='Journal Entry'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reversed_journal_entry',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_invoices', to='accounting.journalentry', verbose_name='Reversed Journal Entry'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
