# Generated by Django 6.0.2 on 2026-04-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_journal_entry_invoice_reversed_journal_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('damage_fee', 'Damage Fee'), ('traffic_fee', 'Traffic Fee'), ('late_fee', 'Late Fee'), ('other', 'Other')], max_length=20, verbose_name='Fee Type'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fee_type_other',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other (specify)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_quick_fee',
            field=models.BooleanField(default=False, help_text='Enable for simple fee invoices (Damage / Traffic / Late fee). Customer fields are not required.', verbose_name='Quick Fee Invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Customer Name'),
        ),
    ]
