# Generated by Django 6.0.2 on 2026-03-18 09:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_no', models.CharField(max_length=30, unique=True)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10)),
                ('source_app', models.CharField(blank=True, max_length=50)),
                ('source_model', models.CharField(blank=True, max_length=50)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_postable', models.BooleanField(default=True, help_text='If False, this is a group/header account and cannot receive journal lines.')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('fuel', 'Fuel'), ('salary', 'Salary'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('card', 'Card/POS')], default='cash', max_length=20)),
                ('vehicle_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('branch_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10)),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounting.account')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_record', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_items', to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Item',
                'verbose_name_plural': 'Journal Items',
            },
        ),
    ]
