# Generated by Django 6.0.2 on 2026-03-18 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('branches', '0001_initial'),
        ('vehicles', '0002_alter_vehicle_options_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='branches.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='vehicles.vehicle', verbose_name='Vehicle'),
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='expense_attachments/%Y/%m/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounting.expense', verbose_name='Expense')),
            ],
            options={
                'verbose_name': 'Expense Attachment',
                'verbose_name_plural': 'Expense Attachments',
                'ordering': ['-id'],
            },
        ),
    ]
