# Generated by Django 6.0.2 on 2026-03-18 11:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_expense_branch_id_remove_expense_vehicle_id_and_more'),
        ('branches', '0001_initial'),
        ('vehicles', '0002_alter_vehicle_options_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('revenue_date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('rental', 'Rental Revenue'), ('extension', 'Extension Revenue'), ('late_fee', 'Late Fee'), ('damage_recovery', 'Damage Recovery'), ('traffic_fine_recovery', 'Traffic Fine Recovery'), ('other', 'Other')], default='rental', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('card', 'Card/POS')], default='cash', max_length=20)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenues', to='branches.branch', verbose_name='Branch')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_record', to='accounting.journalentry')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenues', to='accounting.account')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenues', to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Revenue',
                'verbose_name_plural': 'Revenues',
                'ordering': ['-revenue_date', '-id'],
            },
        ),
    ]
