# Generated by Django 6.0.2 on 2026-03-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_expense_reference_alter_journalentry_entry_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalitem',
            options={},
        ),
    ]
