# Generated by Django 6.0.2 on 2026-03-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_journalitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalitem',
            options={'verbose_name': 'Journal Item', 'verbose_name_plural': 'Journal Items'},
        ),
        migrations.AddConstraint(
            model_name='journalitem',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='journalitem_debit_credit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='journalitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('debit', 0), ('credit__gt', 0)), _connector='OR'), name='journalitem_exactly_one_side_positive'),
        ),
    ]
