# Generated by Django 6.0.2 on 2026-04-02 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_journalentry_exchange_rate_date_and_more'),
        ('branches', '0001_initial'),
        ('vehicles', '0006_alter_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalitem',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_items', to='branches.branch', verbose_name='Branch (Analytical)'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_items', to='vehicles.vehicle', verbose_name='Vehicle (Analytical)'),
        ),
    ]
