# Generated by Django 6.0.2 on 2026-04-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_add_iqd_cash_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalitem',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Original Amount'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='original_currency_code',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('IQD', 'Iraqi Dinar'), ('SYP', 'Syrian Pound'), ('AED', 'UAE Dirham')], default='USD', max_length=3, verbose_name='Currency'),
        ),
    ]
