# Generated by Django 6.0.2 on 2026-03-04 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0003_alter_rental_daily_rate_alter_rental_net_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('method', models.CharField(choices=[('cash', 'نقدي'), ('transfer', 'تحويل بنكي'), ('card', 'بطاقة')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('paid', 'مدفوع بالكامل'), ('partial', 'دفعة جزئية'), ('unpaid', 'غير مدفوع')], max_length=20, verbose_name='الحالة')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.rental', verbose_name='العقد')),
            ],
        ),
    ]
