# Generated by Django 6.0.2 on 2026-03-09 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_alter_payment_amount_paid_and_more'),
        ('rentals', '0005_rentalattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='rentals.rental', verbose_name='Rental Operation'),
        ),
    ]
