# Generated by Django 6.0.2 on 2026-03-18 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('payments', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='accounting_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10, verbose_name='Accounting State'),
        ),
        migrations.AddField(
            model_name='payment',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_record', to='accounting.journalentry', verbose_name='Journal Entry'),
        ),
    ]
