# Generated by Django 6.0.2 on 2026-03-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_options_payment_reference_and_more'),
        ('rentals', '0015_rental_deposit_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Refund Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Refunded'), ('refunded', 'Refunded'), ('withheld', 'Withheld')], default='pending', max_length=20, verbose_name='Status')),
                ('refund_date', models.DateTimeField(auto_now_add=True, verbose_name='Refund Date')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer')], default='cash', max_length=50, verbose_name='Method')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_refunds', to='rentals.rental', verbose_name='Rental')),
            ],
        ),
    ]
