# Generated by Django 6.0.2 on 2026-03-23 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_expense_reference_alter_journalentry_entry_no_and_more'),
        ('payments', '0007_depositrefund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.journalentry', verbose_name='Journal Entry'),
        ),
    ]
