# Generated by Django 6.0.2 on 2026-03-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_depositrefund_journal_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, unique=True, verbose_name='Receipt Reference'),
        ),
    ]
