# Generated by Django 6.0.2 on 2026-04-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Amount USD'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency_code',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('IQD', 'Iraqi Dinar'), ('SYP', 'Syrian Pound'), ('AED', 'UAE Dirham')], default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate_date',
            field=models.DateField(blank=True, null=True, verbose_name='Exchange Rate Date'),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate_to_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Exchange Rate To USD'),
        ),
    ]
