# Generated by Django 6.0.2 on 2026-04-03 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_journalitem_branch_journalitem_vehicle'),
        ('payments', '0011_payment_amount_usd_payment_currency_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Refund Amount')),
                ('refund_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Refund Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Refund Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_refund_record', to='accounting.journalentry', verbose_name='Refund Journal Entry')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund_record', to='payments.payment', verbose_name='Original Payment')),
            ],
            options={
                'verbose_name': 'Payment Refund',
                'verbose_name_plural': 'Payment Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DepositRefund',
        ),
    ]
