# Generated by Django 6.0.2 on 2026-03-09 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-id'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_odometer',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Odometer (KM)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_service_odometer',
            field=models.PositiveIntegerField(default=0, verbose_name='Last Service Odometer'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_interval',
            field=models.PositiveIntegerField(default=5000, verbose_name='Service Every (KM)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch', verbose_name='Branch / City'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Daily Price'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Plate Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance'), ('service', 'Service')], default='available', max_length=20, verbose_name='Vehicle Status'),
        ),
    ]
