# Generated by Django 6.0.2 on 2026-03-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_options_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='annual_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Annual Inspection Date'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_fuel_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Current Fuel Level'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Deposit Amount'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Engine Number'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='extra_km_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Extra KM Price'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=20, null=True, verbose_name='Fuel Type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_company',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Insurance Company'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Insurance Expiry'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance Policy Number'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='key_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Key Count'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_service_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Service Date'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Price'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='next_service_odometer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Next Service Odometer'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ownership_type',
            field=models.CharField(choices=[('company', 'Company Owned'), ('external', 'External / Third Party')], default='company', max_length=20, verbose_name='Ownership Type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchase Price'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Registration Expiry'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seats',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Seats'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20, null=True, verbose_name='Transmission'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chassis / VIN Number'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='weekly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weekly Price'),
        ),
    ]
