# Generated by Django 6.0.2 on 2026-03-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicledocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('internal_use', 'Internal Use'), ('rented', 'Rented'), ('maintenance', 'Maintenance'), ('service', 'Service'), ('stolen', 'Stolen'), ('out_of_service', 'Out of Service'), ('accident', 'Accident'), ('sold', 'Sold')], default='available', max_length=20, verbose_name='Vehicle Status'),
        ),
    ]
