# Generated by Django 6.0.2 on 2026-03-27 20:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0006_alter_vehicle_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150, verbose_name='Employee Name')),
                ('employee_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee Phone')),
                ('purpose', models.CharField(choices=[('delivery', 'Delivery'), ('manager_use', 'Manager Use'), ('workshop', 'Workshop'), ('transfer', 'Transfer'), ('other', 'Other')], default='other', max_length=30, verbose_name='Purpose')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date & Time')),
                ('expected_return_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Expected Return Date & Time')),
                ('actual_return_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Actual Return Date & Time')),
                ('pickup_odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pickup Odometer')),
                ('return_odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Return Odometer')),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Usage Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicle_usages', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_usages', to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Usage',
                'verbose_name_plural': 'Vehicle Usage',
                'ordering': ['-start_datetime', '-id'],
            },
        ),
    ]
