# Generated by Django 6.0.2 on 2026-03-25 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0016_rental_deposit_journal_entry'),
        ('vehicles', '0005_vehicledocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_date', models.DateField(verbose_name='Violation Date')),
                ('violation_type', models.CharField(max_length=150, verbose_name='Violation Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(choices=[('due', 'Due from Customer'), ('collected', 'Collected from Customer'), ('paid_to_government', 'Paid to Government')], default='due', max_length=30, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('collected_from_customer_date', models.DateField(blank=True, null=True, verbose_name='Collected From Customer Date')),
                ('paid_to_government_date', models.DateField(blank=True, null=True, verbose_name='Paid To Government Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_fine_records', to='rentals.rental', verbose_name='Rental Contract')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traffic_fine_records', to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Traffic Fine',
                'verbose_name_plural': 'Traffic Fines',
                'ordering': ['-violation_date', '-id'],
            },
        ),
    ]
