# Generated by Django 6.0.2 on 2026-03-25 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_journalitem_options'),
        ('traffic_fines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficfine',
            name='customer_collection_journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traffic_fine_customer_collection_record', to='accounting.journalentry', verbose_name='Customer Collection Journal Entry'),
        ),
        migrations.AddField(
            model_name='trafficfine',
            name='government_payment_journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traffic_fine_government_payment_record', to='accounting.journalentry', verbose_name='Government Payment Journal Entry'),
        ),
    ]
