# Generated by Django 6.0.2 on 2026-04-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exchangerate',
            name='unique_currency_per_day',
        ),
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='exchange_ra_currenc_1da57b_idx',
            old_name='exchangerate_currency_date_idx',
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('currency_code', 'effective_date')},
        ),
    ]
