# Generated by Django 6.0.2 on 2026-03-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "General Ledger",
                "verbose_name_plural": "📖 General Ledger",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IncomeStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Income Statement",
                "verbose_name_plural": "📊 Income Statement",
                "managed": False,
            },
        ),
    ]
